### ISSUE TITLE
VVV Dashboard version check & usage tracking

### ISSUE THREAD

**Issue by topdown** [topdown/VVV-Dashboard#14]
I am thinking about moving the version check for VVV-Dashboard to my server so I can track how many actual users we have. Note: would probable collect some simple data like IP address.

Anyone see a personal issue with this?
Would like some input.

**Comment by josephfusco** [comment]
IMO I don't think it would be that accurate of a sample. A handful of people would just remove stuff like that, or already have stripped down the dashboard and don't ever plan to update.

**Comment by topdown** [comment]
They don't need to strip it down, they could just use an older version. Maybe I'll roll back and make a tag release of the older version.

Anyway, I have plans to add settings to shut features off that people don't want to look at or use.
Maybe next release.

**Comment by josephfusco** [comment]
I think that would be great. Just a vanilla version as well. :)

**Comment by topdown** [comment]
Already done, made a minimal version just a bit ago https://github.com/topdown/VVV-Dashboard/releases/tag/minimal
Its before I added all of the features the last month or so.
