### ISSUE TITLE
Actions not available for some sites

### ISSUE THREAD

**Issue by spigotdesign** [topdown/VVV-Dashboard#20]
Most sites have all the actions available, but some do not. Not sure what's different about this one: utahfostercare.dev

http://spig.io/3s3836240H0A

Fantastic dashboard for VVV, thanks for the great work.

**Comment by topdown** [comment]
The ones that do not have all of the buttons is because the wp-config was not found.
Is that site fully installed? or does it have a none typical install path?

**Comment by spigotdesign** [comment]
Standard install, I've been developing it normally for a week or so.

**Comment by topdown** [comment]
That is odd, have not seen that happen with a normal WP install only with odd template installs that use custom paths.

Did you try purging the hosts? Should not make a difference since the cache is only 24 hours, but just trying some ideas. Watch the cache folder when you purge and make sure the hosts file is gone.

**Comment by spigotdesign** [comment]
I've purged and watched the file dis/re-appear. This isn't a huge deal so maybe we should chalk it up to weirdness?

**Comment by topdown** [comment]
Could. But I just don't want people to be missing things that should work and have a bunch of tickets about the same issue.

So, could you get me some more info.
1. Operating system, eg Windows, Mac, etc..
2. Screenshot of the file structure including the dashboard path and that WordPress install.

Thanks

**Comment by spigotdesign** [comment]
OS X 10.11.2

Dashboard: http://spig.io/1G2p0W1J0c29
WP Install: http://spig.io/112j1K1K2L1G

**Comment by ereckers** [comment]
I'm having the same general issue. Is it a prerequisite to have a domain in the form of `project.dev`?

I've got a number of domain styles, for example:

```
www.project1.dev
dev.project2.ai
```

I took a look at file `libs/vvv-dash-hosts.php` `public function get_paths` and saw that it relies on `$hosts` and takes the string up to the first `.` and and checks our `VVV_WEB_ROOT` for the `htdocs` and `public` directories.

I also have instances in which I'll name the project directories something weird like `/VVV_WEB_ROOT/project-v2/` but still have a domain mapped to it like `www.project.com`. Looks like we have to keep a pretty strict naming convention at the moment.

**Comment by topdown** [comment]
It is pretty strict, it used the domain listed in the vvv-hosts file.
But other areas specifically look for .dev and like you said the first .
In the future when I work on that area again I'll look into a better way to handle it and test alternate domains like you have.
I just never strayed from VVV's default setup of .dev so I never thought about it.

**Comment by ereckers** [comment]
Thanks for the clarification. I looked around a little last night, but couldn't figure out a quick way to get it all together. Thanks for keeping this project going by the way!

**Comment by topdown** [comment]
@spigotdesign If you are still using this and having issues with actions not working.
Could you give branch refactor-actions a try. If you have a fork just make sure its fully updated.

**Comment by spigotdesign** [comment]
@topdown the refactor-actions branch does bring back the actions for the one that was broken. 

The table styles are a bit off, but other than that it works!

http://spig.io/3c1I3S3T3l3l

**Comment by topdown** [comment]
The table is messed up because of the Sites column in the first row.
What site is that suppose to be?

**Comment by spigotdesign** [comment]
Ah, that's an _archive directory I created to stash older projects. I'll have to stash them elsewhere I guess.

**Comment by topdown** [comment]
Well, glad you did it, because now I know it caused a bug/issue so I can add checking for it.
Maybe ignore any directory that starts with _underscore

**Comment by spigotdesign** [comment]
Ignoring a directory would also remove it from the dashboard list no? The 'archived' sites appeared in the list as 'uninstalled'  previously.

**Comment by topdown** [comment]
Well, it just needs to be handled properly. I didn't think to test for that type of situation.
Now I know to, and can figure out what to do with them.
Either ignore that type of directory or list it as an archive or something, maybe with a setting to show/hide it.

**Comment by topdown** [comment]
@spigotdesign do a pull on `refactor-actions` should fix the _archive issue.

**Comment by spigotdesign** [comment]
@topdown Very nice, thank you!!

**Comment by topdown** [comment]
Just a little note: I merged `refactor-actions` into `develop` for a week or so before I release and merge to master. So all of the changes are now in develop also with the latest features.
I also deleted `refactor-actions` branch so you will want to switch to either develop or master.

**Comment by topdown** [comment]
This is all merged into master and develop and in the latest release.
Closing this for now. Feel free to open a new ticket if you have any more issues. Thanks
