### ISSUE TITLE
Versioning issue between my VVV and Dashboard 0.1.7

### ISSUE THREAD

**Issue by 1bigidea** [topdown/VVV-Dashboard#33]
My Dashboard is missing a lot of indexes
https://www.dropbox.com/s/m0ifmwmjtayq43d/Screenshot%202016-05-28%2014.00.14.png?dl=0

while my $host_info file looks like this
Array
(
    [1bigidea] => Array
        (
            [host] => 1bigidea.dev
            [debug] => true
            [is_wp] => true
            [version] => 4.3.1

        )

    [ballers] => Array
        (
            [host] => ballers.dev
            [debug] => true
            [is_wp] => true
            [version] => 4.2.4

        )

    [bizcor-bookmyvacay] => Array
        (
            [host] => bmv.dev
            [debug] => true
            [is_wp] => true
            [version] => 
        )

**Comment by topdown** [comment]
Did you Purge the Hosts? Because there is a lot of info missing there.

**Comment by 1bigidea** [comment]
Thanks for the prompt response, Jeff.
Purging the plugins actually solved the issue.
