### ISSUE TITLE
errors showing in dashboard

### ISSUE THREAD

**Issue by nicholastillman** [topdown/VVV-Dashboard#39]
I am getting this in the dashboard:

Last 10 PHP Errors
[16-Jun-2016 19:10:13 UTC] PHP Warning: file_put_contents(cache/host-sites-1466104213.txt): failed to open stream: No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 87

[16-Jun-2016 19:10:13 UTC] PHP Warning: Invalid argument supplied for foreach() 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 167

[16-Jun-2016 19:10:13 UTC] PHP Warning: scandir(): (errno 2): No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

[16-Jun-2016 19:10:13 UTC] PHP Warning: scandir(cache/): failed to open dir: No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

[16-Jun-2016 19:10:13 UTC] PHP Warning: Invalid argument supplied for foreach() 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 167

[16-Jun-2016 19:10:13 UTC] PHP Warning: scandir(): (errno 2): No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

[16-Jun-2016 19:10:13 UTC] PHP Warning: scandir(cache/): failed to open dir: No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

Suggestions?

Thanks for this great tool to use in development by the way.

**Comment by topdown** [comment]
create directory `www/default/dashboard/cache`
If it does not exist
Then chmod it to 777

If that does not work you may have to do it in the box
```
vagrant ssh
mkdir /srv/www/default/dashboard/vvv_dash/cache
chmod 777 /srv/www/default/dashboard/vvv_dash/cache
exit
```
Thanks

**Comment by nicholastillman** [comment]
Tried but neither process worked. Ill try uninstalling then reinstalling.

**Comment by topdown** [comment]
Ok, thats weird, I would have thought it would have fixed it.
I'm going to run some tests also to see if I can replicate the issue.

**Comment by nicholastillman** [comment]
Thanks for your help

**Comment by topdown** [comment]
Are you just seeing these errors in the Last 10 Errors or are you seeing them on screen?

The last 10 errors will always be there as they are pulled from the server error.log

**Comment by topdown** [comment]
This startup issue should be fixed in the latest develop and master branches now.

Note: the errors will still show in the latest 10 errors box, which is just pulled from the logs. Its not happening every time.
The only way to make that go away is to delete the log.
Go to the directory you have this vagrant setup and open the log directory.
Delete `php_errors.log`

That will empty the Last 10 Errors box.

**Comment by nicholastillman** [comment]
In the Last 10, It doesn't show on my work computer, I'll delete the errors log. Will the log regenerate if any errors occur? I see it as helpful in debugging, just was't sure what was causing it. Again thanks for your help, and for a great resource!

**Comment by topdown** [comment]
Yes, it regenerates when the server detects PHP errors.

**Comment by topdown** [comment]
Closing this for now. Feel free to open a new ticket if you have any more issues. Thanks
