### ISSUE TITLE
Initial setup problems

### ISSUE THREAD

**Issue by rtpHarry** [topdown/VVV-Dashboard#4]
Probably more a problem with my setup than this repo but thought I would post it here in case it is an issue with your setup instructions:

I am in Windows, running Cmder, Git installed, Administrator permissions, in the www folder as instructed. Typed this:

    git clone git@github.com:topdown/VVV-Dashboard.git dashboard

And it wouldn't work for me:

    Cloning into 'dashboard'...
    The authenticity of host 'github.com (192.30.252.130)' can't be established.
    RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
    Are you sure you want to continue connecting (yes/no)? yes
    Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

**Comment by rtpHarry** [comment]
After reading the [documentation](https://help.github.com/articles/which-remote-url-should-i-use) I tried the https url instead:

    git clone https://github.com/topdown/VVV-Dashboard.git dashboard

and that worked first time. I don't know if its just something I don't have setup correctly or if you need different instructions for Windows?

**Comment by robneu** [comment]
I think the docs just need updated here. Using the https URL should be fine cross-platform.

**Comment by topdown** [comment]
I think your right. My mistake in the instructions.
I will get them updated, thanks.
