### ISSUE TITLE
Updated to latest and dashboard does not work right

### ISSUE THREAD

**Issue by thatryan** [topdown/VVV-Dashboard#43]
Saw a notice to update so pulled latest, and it was working great, however now it appears broken and unusable. Unsure how to proceed.

![2016-07-06 at 11 40 am](https://cloud.githubusercontent.com/assets/26583/16630326/c7022342-436e-11e6-89ef-ff5b9681ad1d.png)

**Comment by topdown** [comment]
Purge the cache, or just go into the dashboard directory and delete the files in the cache directory  manually.

**Comment by thatryan** [comment]
DOH! Thank you.
