### ISSUE TITLE
Notice version check should use version_compare

### ISSUE THREAD

**Issue by danieliser** [topdown/VVV-Dashboard#45]
views/partials/notices.php line 22 should be:

if ( version_compare( VVV_DASH_VERSION, version_check(), '<' ) ) {

Otherwise it always shows needing an update. Using a standard VVV_DASH_VERSION < version_check() won't work due to it not being a true float. IE 0.1.7 cannot be compared as a number due to its second decimal point.

**Comment by topdown** [comment]
I have been meaning to fix that. Thanks for the ticket.
