### ISSUE TITLE
Error message and some sites appear as not installed

### ISSUE THREAD

**Issue by fxbenard** [topdown/VVV-Dashboard#49]
I'm using latest version

How can I fix this message error

PHP Warning: Invalid argument supplied for foreach()
in /srv/www/default/dashboard/views/partials/hosts-list2.php on line 80

Thanks for such a nice UI to manage our sites

**Comment by topdown** [comment]
Could you go to the dashboard directory and do a `git pull` to update
Then go in the cache folder and delete everything in there.

**Comment by fxbenard** [comment]
Hi, just did it

Version: 0.1.9, Branch: f3b850f master installed

and

[01-Dec-2016 21:22:22 UTC] PHP Warning: Invalid argument supplied for foreach()
in /srv/www/default/dashboard/views/partials/hosts-list2.php on line 80

**Comment by topdown** [comment]
Interesting, that no longer be on line 80 but 81
Do you have any multi-sites configured?

**Comment by fxbenard** [comment]
Yes single and multisite configured
Nope a working install (vv + my own)

Deleting doesn't help, tried it several time

I'm on your Gitter ;)
