### ISSUE TITLE
I get 404

### ISSUE THREAD

**Issue by kyle9876** [topdown/VVV-Dashboard#8]
All my urls through vagrant are working except http://vvv.dev or http://vvv. Can't figure out why the dashboard isn't working, I'm getting a 404.

I did the following commands (my vvv install is ~/vagrant-local)
cd ~/vagrant-local
git clone git@github.com:topdown/VVV-Dashboard.git dashboard
cp ~/vagrant-local/www/dashboard/dashboard-custom.php ~/vagrant-local/www/default/
cp ~/vagrant-local/www/dashboard/style.css ~/vagrant-local/www/default/style.css

then vagrant up.

**Comment by cipas** [comment]
same issue here, vvv.dev get redirected to http://vvv.dev/dashboard/index.php and then 404.

**Comment by cipas** [comment]
Ok so I figure it out, I moved dashboard folder to default folder.

cd ~/vagrant-local
mv dashboard default/dashboard

And works for me.

**Comment by topdown** [comment]
They must have changed available paths in VVV or something. I'll have to update my install and see what happens.

**Comment by topdown** [comment]
Edit: yeah I see what you did. Yes the dashboard/ needs to be in the default/ directory.

**Comment by cipas** [comment]
cool. Maybe it's better to have a separate site then use default one, what do you think ?

**Comment by topdown** [comment]
In the future there possibly is going to be a command installer for this dashboard directly into VVV as an option or maybe even the default dashboard itself. Its been an ongoing discussion and a pull request for it. https://github.com/Varying-Vagrant-Vagrants/VVV/pull/609

**Comment by topdown** [comment]
Closing this. If you are still having issues feel free to reopen or create a new issue.
